sonar.projectKey=curriculum-v
sonar.projectName=curriculum-v
sonar.sources=src,app.py
sonar.exclusions=**/data/resume.yaml
sonar.issue.ignore.multicriteria=e1,e2,e3,e4
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S6767
sonar.issue.ignore.multicriteria.e1.resourceKey=src/components/CV.jsx
sonar.issue.ignore.multicriteria.e2.ruleKey=javascript:S6479
sonar.issue.ignore.multicriteria.e2.resourceKey=src/components/CV.jsx
sonar.issue.ignore.multicriteria.e3.ruleKey=javascript:S2245
sonar.issue.ignore.multicriteria.e3.resourceKey=src/components/Background.jsx
sonar.issue.ignore.multicriteria.e4.ruleKey=javascript:S6770
sonar.issue.ignore.multicriteria.e4.resourceKey=src/App.jsx
sonar.issue.ignore.multicriteria.e5.ruleKey=javascript:S6770
sonar.issue.ignore.multicriteria.e5.resourceKey=src/components/CV.test.jsx
