name: curriculum-v
namespace: curriculum-v

imageTag: "1.0.1"

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

schedulingExclusion:
  excludedNodeLabel: "node-role.kubernetes.io/control-plane"

httpRoute:
  hostname: "cv.theit.cc"
  ngf:
    name: "nginx"
    namespace: "nginx-gateway-fabric"

