apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: curriculum-v
  namespace: argo-cd
spec:
  destination:
    namespace: curriculum-v
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: helm/curriculum-v
    repoURL: https://github.com/kamkry-zz/curriculumV.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - CreateNamespace=true
